export {default as Main} from './Main'
export {default as NavBar} from './NavBar'
export {default as About} from './About'
export {default as Projects} from './Projects'
export {default as ContactMe} from './ContactMe'